#
# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Fabio Fehr <fabio.fehr@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
#

name: nvr
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11 # Free BSD - https://www.python.org/
  - pytorch::pytorch=2.1 # BSD3 - https://pytorch.org/
  - pytorch::pytorch-cuda=11.8 # BSD3 - https://pytorch.org/
  - nvidia::cuda=11.8 # MIT - https://docs.nvidia.com/cuda/eula/index.html
  - pip # MIT - https://github.com/pypa/pip
  - matplotlib # BSD - https://github.com/pypa/pip
  - transformers # apache2.0 - https://pypi.org/project/transformers/
  - datasets # Apache 2.0 - https://pypi.org/project/datasets/
  - wandb # MIT https://wandb.ai/site
  - lightning # Apache License 2.0 - https://pytorch-lightning.readthedocs.io/en/stable/
  - pytest # MIT - https://docs.pytest.org/en/7.1.x/index.html
  - python-dotenv # BSD-3-Clause - https://pypi.org/project/python-dotenv/
  - plotly # MIT - https://plotly.com/python/
  - torchmetrics # Apache 2.0 - https://github.com/Lightning-AI/torchmetrics
  - nltk # Apache 2.0 - https://www.nltk.org/
  - py7zr #  GNU Lesser General Public License - https://pypi.org/project/py7zr/
  - bitsandbytes # MIT - https://github.com/TimDettmers/bitsandbytes
  - pip:
      - sentencepiece # Apache 2.0 - https://pypi.org/project/sentencepiece/
      - ../nvib-private/. # GPLv3
