#
# SPDX-FileCopyrightText: Copyright © 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-FileContributor: Fabio Fehr <fabio.fehr@idiap.ch>
#
# SPDX-License-Identifier: GPL-3.0-only
#

experiment_name: marian_ende_iwslt
project_name: project_name
entity: xxx # fill in your own
output_dir: outputs
model_path: null
count: 1
# DATA - gaussian, xsum, cnn_dailymail... etc
data: iwslt2017
src_lang: en
tgt_lang: de
emp_data: opus100
emp_perc: 1.0
num_workers: 4
val_perc: 1
seed: 42
fast_dev_run: null
quantisation: null
test: null
# MODEL
model: NVIBMARIAN
batch_size: 32
kld_lambda: 1
klg_lambda: 1
mu_tau: 1
# WandB Sweep
method: random # bayes, grid, random
metric:
  name: bleu_val
  goal: maximize
parameters:
  # ALPHA
  alpha_tau_e:
    min: -1.0
    max: 3.0
  alpha_tau_c:
    min: -8.0
    max: 0.0
  alpha_tau_d:
    min: 0.0
    max: 3.0
  # SIGMA
  stdev_tau_e:
    min: 0.0
    max: 0.05
  stdev_tau_c:
    min: 0.0
    max: 1.75
  stdev_tau_d:
    min: 0.0
    max: 0.5
